title: "WG(w311ang)的博客"
description: "一个基于MDUI的Jekyll博客"
url: blog.runz.tk
baseurl: ""
author: "W311anG"
paginate: 5
paginate_path: "/blog/page:num/"


# Build settings
theme: jekyll-theme-mdui
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
